//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFoodResturentWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinalResult_Table
    {
        public int Id { get; set; }
        public Nullable<int> InterArrivalTime { get; set; }
        public Nullable<int> ArrivalTime { get; set; }
        public Nullable<int> ServiceTime { get; set; }
        public Nullable<int> ServiceStartTime { get; set; }
        public Nullable<int> ServiceEndTime { get; set; }
        public Nullable<int> WaitingTime { get; set; }
        public Nullable<int> ServerIdelTime { get; set; }
    }
}
